// <auto-generated />
using System;
using BelanjaYuk.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BelanjaYuk.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260802061231_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BelanjaYuk.Domain.Entities.LtCategory", b =>
                {
                    b.Property<string>("IdCategory")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUp")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UserIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("UserUp")
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("IdCategory");

                    b.ToTable("LtCategory", (string)null);
                });

            modelBuilder.Entity("BelanjaYuk.Domain.Entities.LtGender", b =>
                {
                    b.Property<string>("IdGender")
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUp")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UserIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("UserUp")
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("IdGender");

                    b.ToTable("LtGender", (string)null);
                });

            modelBuilder.Entity("BelanjaYuk.Domain.Entities.LtPayment", b =>
                {
                    b.Property<string>("IdPayment")
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUp")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("UserUp")
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("IdPayment");

                    b.ToTable("LtPayment", (string)null);
                });

            modelBuilder.Entity("BelanjaYuk.Domain.Entities.MsProduct", b =>
                {
                    b.Property<string>("IdProduct")
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUp")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DiscountProduct")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("IdCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("IdUserSeller")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductDesc")
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("UserIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("UserUp")
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("IdProduct");

                    b.HasIndex("IdCategory");

                    b.HasIndex("IdUserSeller");

                    b.ToTable("MsProduct", (string)null);
                });

            modelBuilder.Entity("BelanjaYuk.Domain.Entities.MsUser", b =>
                {
                    b.Property<string>("IdUser")
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Firstname");

                    b.Property<string>("IdGender")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserUp")
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("IdUser");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdGender");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("MsUser", (string)null);
                });

            modelBuilder.Entity("BelanjaYuk.Domain.Entities.MsUserPassword", b =>
                {
                    b.Property<string>("IdUserPassword")
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUp")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("UserUp")
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("IdUserPassword");

                    b.HasIndex("IdUser")
                        .IsUnique();

                    b.ToTable("MsUserPassword", (string)null);
                });

            modelBuilder.Entity("BelanjaYuk.Domain.Entities.MsUserSeller", b =>
                {
                    b.Property<string>("IdUserSeller")
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUp")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SellerCode")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SellerDesc")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("UserUp")
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("IdUserSeller");

                    b.HasIndex("IdUser");

                    b.HasIndex("SellerCode")
                        .IsUnique()
                        .HasFilter("[SellerCode] IS NOT NULL");

                    b.ToTable("MsUserSeller", (string)null);
                });

            modelBuilder.Entity("BelanjaYuk.Domain.Entities.TrBuyerCart", b =>
                {
                    b.Property<string>("IdBuyerCart")
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUp")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<string>("UserIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("UserUp")
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("IdBuyerCart");

                    b.HasIndex("IdProduct");

                    b.HasIndex("IdUser", "IdProduct");

                    b.ToTable("TrBuyerCart", (string)null);
                });

            modelBuilder.Entity("BelanjaYuk.Domain.Entities.TrBuyerTransaction", b =>
                {
                    b.Property<string>("IdBuyerTransaction")
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IdPayment")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("RatingComment")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("UserIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("UserUp")
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("IdBuyerTransaction");

                    b.HasIndex("IdPayment");

                    b.HasIndex("IdUser");

                    b.ToTable("TrBuyerTransaction", (string)null);
                });

            modelBuilder.Entity("BelanjaYuk.Domain.Entities.TrBuyerTransactionDetail", b =>
                {
                    b.Property<string>("IdBuyerTransactionDetail")
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUp")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DiscountProduct")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("IdBuyerTransaction")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("IdProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("PriceProduct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("RatingComment")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("UserIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("UserUp")
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("IdBuyerTransactionDetail");

                    b.HasIndex("IdBuyerTransaction");

                    b.HasIndex("IdProduct");

                    b.ToTable("TrBuyerTransactionDetail", (string)null);
                });

            modelBuilder.Entity("BelanjaYuk.Domain.Entities.TrHomeAddress", b =>
                {
                    b.Property<string>("IdHomeAddress")
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("IdhomeAddress");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUp")
                        .HasColumnType("datetime2");

                    b.Property<string>("HomeAddressDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimaryAddress")
                        .HasColumnType("bit");

                    b.Property<string>("Kecamatan")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KodePos")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("KotaKabupaten")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("KotaKabupaten");

                    b.Property<string>("Provinsi")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("UserUp")
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("IdHomeAddress");

                    b.HasIndex("IdUser");

                    b.ToTable("TrHomeAddress", (string)null);
                });

            modelBuilder.Entity("BelanjaYuk.Domain.Entities.TrProductImages", b =>
                {
                    b.Property<string>("IdProductImages")
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTime>("DateIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUp")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserIn")
                        .IsRequired()
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("UserUp")
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("IdProductImages");

                    b.HasIndex("IdProduct");

                    b.ToTable("TrProductImages", (string)null);
                });

            modelBuilder.Entity("BelanjaYuk.Domain.Entities.MsProduct", b =>
                {
                    b.HasOne("BelanjaYuk.Domain.Entities.LtCategory", "Category")
                        .WithMany()
                        .HasForeignKey("IdCategory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BelanjaYuk.Domain.Entities.MsUserSeller", "Seller")
                        .WithMany()
                        .HasForeignKey("IdUserSeller")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("BelanjaYuk.Domain.Entities.MsUser", b =>
                {
                    b.HasOne("BelanjaYuk.Domain.Entities.LtGender", "Gender")
                        .WithMany()
                        .HasForeignKey("IdGender")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("BelanjaYuk.Domain.Entities.MsUserPassword", b =>
                {
                    b.HasOne("BelanjaYuk.Domain.Entities.MsUser", "User")
                        .WithOne("Password")
                        .HasForeignKey("BelanjaYuk.Domain.Entities.MsUserPassword", "IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BelanjaYuk.Domain.Entities.MsUserSeller", b =>
                {
                    b.HasOne("BelanjaYuk.Domain.Entities.MsUser", null)
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BelanjaYuk.Domain.Entities.TrBuyerCart", b =>
                {
                    b.HasOne("BelanjaYuk.Domain.Entities.MsProduct", "Product")
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BelanjaYuk.Domain.Entities.MsUser", null)
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BelanjaYuk.Domain.Entities.TrBuyerTransaction", b =>
                {
                    b.HasOne("BelanjaYuk.Domain.Entities.LtPayment", "Payment")
                        .WithMany()
                        .HasForeignKey("IdPayment")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BelanjaYuk.Domain.Entities.MsUser", null)
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("BelanjaYuk.Domain.Entities.TrBuyerTransactionDetail", b =>
                {
                    b.HasOne("BelanjaYuk.Domain.Entities.TrBuyerTransaction", "Transaction")
                        .WithMany("Details")
                        .HasForeignKey("IdBuyerTransaction")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BelanjaYuk.Domain.Entities.MsProduct", "Product")
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("BelanjaYuk.Domain.Entities.TrHomeAddress", b =>
                {
                    b.HasOne("BelanjaYuk.Domain.Entities.MsUser", null)
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BelanjaYuk.Domain.Entities.TrProductImages", b =>
                {
                    b.HasOne("BelanjaYuk.Domain.Entities.MsProduct", "Product")
                        .WithMany("Images")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BelanjaYuk.Domain.Entities.MsProduct", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("BelanjaYuk.Domain.Entities.MsUser", b =>
                {
                    b.Navigation("Password");
                });

            modelBuilder.Entity("BelanjaYuk.Domain.Entities.TrBuyerTransaction", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
